FROM python:3.13.7-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN which ffmpeg

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "highlight/highlight_agent.py"]