services:
  moderator_ai:
    build: 
      context: .
      dockerfile: dockerfile.moderator
    image: moderator-ai
    container_name: moderator-ai
    ports:
      - 8002:8002
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true