name: Deploy Agent to Agentverse

on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: 'Name of the agent to deploy (must match the run_...py file)'
        required: true
        type: choice
        options:
        - moderator
      agent_seed_secret_name:
        description: 'The name of the GitHub secret for the AGENT_SEED'
        required: true
        type: string
      agent_address_secret_name:
        description: 'The name of the GitHub secret for the AGENT_ADDRESS'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install avctl
        run: pip install avctl

      - name: Deploy to Agentverse
        run: |
          START_COMMAND="python run_${{ github.event.inputs.agent_name }}.py"
          AGENT_SEED_VALUE="${{ secrets[github.event.inputs.agent_seed_secret_name] }}"
          AGENT_ADDRESS_VALUE="${{ secrets[github.event.inputs.agent_address_secret_name] }}"
          
          avctl deploy . \
            --project-name "${{ github.event.inputs.agent_name }}-agent" \
            --agent-address "$AGENT_ADDRESS_VALUE" \
            --start-command "$START_COMMAND" \
            --secret AGENT_SEED="$AGENT_SEED_VALUE" \
            --secret GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
        env:
          AV_API_KEY: ${{ secrets.AV_API_KEY }}